import 'package:flutter/material.dart';
import '../../l10n/app_localizations.dart';

/// Extension to easily access AppLocalizations from BuildContext
extension LocalizationExtension on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this)!;
}

/// Helper class for accessing translations
class AppTranslations {
  static AppLocalizations of(BuildContext context) {
    return AppLocalizations.of(context)!;
  }
}

/// Global translation helper function - t(context, "keyName")
/// Maps key names to translation strings
String t(BuildContext context, String key) {
  final l10n = AppLocalizations.of(context)!;

  switch (key) {
    // App & Navigation
    case 'appName':
      return l10n.appName;
    case 'home':
      return l10n.home;
    case 'stores':
      return l10n.stores;
    case 'orders':
      return l10n.orders;
    case 'profile':
      return l10n.profile;
    case 'cart':
      return l10n.cart;

    // Auth
    case 'login':
      return l10n.login;
    case 'register':
      return l10n.register;
    case 'signIn':
      return l10n.signIn;
    case 'signUp':
      return l10n.signUp;
    case 'welcomeBack':
      return l10n.welcomeBack;
    case 'logout':
      return l10n.logout;

    // Form Fields
    case 'email':
      return l10n.email;
    case 'phoneNumber':
      return l10n.phoneNumber;
    case 'password':
      return l10n.password;
    case 'confirmPassword':
      return l10n.confirmPassword;
    case 'firstName':
      return l10n.firstName;
    case 'lastName':
      return l10n.lastName;
    case 'cardNumber':
      return l10n.cardNumber;
    case 'cardHolder':
      return l10n.cardHolder;
    case 'expiryDate':
      return l10n.expiryDate;
    case 'cvv':
      return l10n.cvv;

    // Buttons & Actions
    case 'save':
      return l10n.save;
    case 'cancel':
      return l10n.cancel;
    case 'delete':
      return l10n.delete;
    case 'edit':
      return l10n.edit;
    case 'update':
      return l10n.update;
    case 'submit':
      return l10n.submit;
    case 'retry':
      return l10n.retry;
    case 'ok':
      return l10n.ok;
    case 'yes':
      return l10n.yes;
    case 'no':
      return l10n.no;
    case 'verify':
      return l10n.verify;
    case 'resendCode':
      return l10n.resendCode;
    case 'addToCart':
      return l10n.addToCart;
    case 'placeOrder':
      return l10n.placeOrder;
    case 'continueShopping':
      return l10n.continueShopping;
    case 'reorder':
      return l10n.reorder;
    case 'trackOrder':
      return l10n.trackOrder;
    case 'remove':
      return l10n.remove;
    case 'setAsDefault':
      return l10n.setAsDefault;

    // Messages & Prompts
    case 'forgotPassword':
      return l10n.forgotPassword;
    case 'dontHaveAccount':
      return l10n.dontHaveAccount;
    case 'alreadyHaveAccount':
      return l10n.alreadyHaveAccount;
    case 'or':
      return l10n.or;
    case 'continueWithGoogle':
      return l10n.continueWithGoogle;
    case 'continueWithFacebook':
      return l10n.continueWithFacebook;
    case 'continueWithApple':
      return l10n.continueWithApple;

    // Home Screen
    case 'deliverTo':
      return l10n.deliverTo;
    case 'searchDishesStores':
      return l10n.searchDishesStores;
    case 'allCategories':
      return l10n.allCategories;
    case 'seeAll':
      return l10n.seeAll;
    case 'openStores':
      return l10n.openStores;
    case 'closedStores':
      return l10n.closedStores;
    case 'popularNearYou':
      return l10n.popularNearYou;

    // Orders
    case 'myOrders':
      return l10n.myOrders;
    case 'ongoing':
      return l10n.ongoing;
    case 'history':
      return l10n.history;
    case 'orderNumber':
      return l10n.orderNumber;
    case 'orderPlaced':
      return l10n.orderPlaced;
    case 'orderConfirmed':
      return l10n.orderConfirmed;
    case 'preparing':
      return l10n.preparing;
    case 'ready':
      return l10n.ready;
    case 'pickedUp':
      return l10n.pickedUp;
    case 'delivered':
      return l10n.delivered;
    case 'cancelled':
      return l10n.cancelled;
    case 'pending':
      return l10n.pending;

    // Cart
    case 'myCart':
      return l10n.myCart;
    case 'editItems':
      return l10n.editItems;
    case 'deliveryAddress':
      return l10n.deliveryAddress;
    case 'total':
      return l10n.total;
    case 'breakdown':
      return l10n.breakdown;
    case 'emptyCart':
      return l10n.emptyCart;
    case 'startShopping':
      return l10n.startShopping;

    // Profile
    case 'myProfile':
      return l10n.myProfile;
    case 'personalInfo':
      return l10n.personalInfo;
    case 'myAddresses':
      return l10n.myAddresses;
    case 'paymentMethods':
      return l10n.paymentMethods;
    case 'notifications':
      return l10n.notifications;
    case 'favorites':
      return l10n.favorites;
    case 'language':
      return l10n.language;
    case 'changingLanguage':
      return l10n.changingLanguage;
    case 'pleaseWait':
      return l10n.pleaseWait;
    case 'helpSupport':
      return l10n.helpSupport;
    case 'termsConditions':
      return l10n.termsConditions;
    case 'privacyPolicy':
      return l10n.privacyPolicy;

    // Addresses
    case 'addresses':
      return l10n.addresses;
    case 'addNewAddress':
      return l10n.addNewAddress;
    case 'noAddresses':
      return l10n.noAddresses;
    case 'addFirstAddress':
      return l10n.addFirstAddress;
    case 'home_address':
      return l10n.home_address;
    case 'work_address':
      return l10n.work_address;
    case 'other_address':
      return l10n.other_address;
    case 'defaultAddress':
      return l10n.defaultAddress;
    case 'deleteAddress':
      return l10n.deleteAddress;
    case 'editAddress':
      return l10n.editAddress;
    case 'addAddress':
      return l10n.addAddress;
    case 'selectFromMap':
      return l10n.selectFromMap;
    case 'address':
      return l10n.address;
    case 'latitude':
      return l10n.latitude;
    case 'longitude':
      return l10n.longitude;
    case 'label':
      return l10n.label;

    // Payment
    case 'payment':
      return l10n.payment;
    case 'cash':
      return l10n.cash;
    case 'creditCard':
      return l10n.creditCard;
    case 'savedCards':
      return l10n.savedCards;
    case 'addNewCard':
      return l10n.addNewCard;
    case 'saveCard':
      return l10n.saveCard;

    // Favorites
    case 'favorites_title':
      return l10n.favorites_title;
    case 'noFavorites':
      return l10n.noFavorites;
    case 'startAddingFavorites':
      return l10n.startAddingFavorites;
    case 'removeFavorite':
      return l10n.removeFavorite;
    case 'removeFromFavorites':
      return l10n.removeFromFavorites;

    // Verification
    case 'verification':
      return l10n.verification;
    case 'verifyAccount':
      return l10n.verifyAccount;
    case 'enterVerificationCode':
      return l10n.enterVerificationCode;
    case 'verificationCode':
      return l10n.verificationCode;
    case 'didntReceiveCode':
      return l10n.didntReceiveCode;
    case 'accountNotVerified':
      return l10n.accountNotVerified;
    case 'verifyToPlaceOrders':
      return l10n.verifyToPlaceOrders;
    case 'verificationRequired':
      return l10n.verificationRequired;
    case 'pleaseVerifyAccount':
      return l10n.pleaseVerifyAccount;
    case 'verifyNow':
      return l10n.verifyNow;

    // Location
    case 'selectLocation':
      return l10n.selectLocation;
    case 'searchLocation':
      return l10n.searchLocation;
    case 'confirmLocation':
      return l10n.confirmLocation;
    case 'currentLocation':
      return l10n.currentLocation;
    case 'locationPermissionDenied':
      return l10n.locationPermissionDenied;
    case 'locationNotFound':
      return l10n.locationNotFound;

    // Store Details
    case 'store':
      return l10n.store;
    case 'menu':
      return l10n.menu;
    case 'reviews':
      return l10n.reviews;
    case 'info':
      return l10n.info;
    case 'rating':
      return l10n.rating;
    case 'deliveryFee':
      return l10n.deliveryFee;
    case 'deliveryTime':
      return l10n.deliveryTime;
    case 'minOrder':
      return l10n.minOrder;
    case 'addedToCart':
      return l10n.addedToCart;
    case 'itemAddedToCart':
      return l10n.itemAddedToCart;

    // Search
    case 'search':
      return l10n.search;
    case 'searchResults':
      return l10n.searchResults;
    case 'noResults':
      return l10n.noResults;
    case 'tryDifferentKeywords':
      return l10n.tryDifferentKeywords;

    // Status & Messages
    case 'error':
      return l10n.error;
    case 'success':
      return l10n.success;
    case 'loading':
      return l10n.loading;

    // Validation
    case 'pleaseEnterEmail':
      return l10n.pleaseEnterEmail;
    case 'pleaseEnterPhone':
      return l10n.pleaseEnterPhone;
    case 'pleaseEnterPassword':
      return l10n.pleaseEnterPassword;
    case 'pleaseEnterFirstName':
      return l10n.pleaseEnterFirstName;
    case 'pleaseEnterLastName':
      return l10n.pleaseEnterLastName;
    case 'passwordsDontMatch':
      return l10n.passwordsDontMatch;
    case 'invalidEmail':
      return l10n.invalidEmail;
    case 'invalidPhone':
      return l10n.invalidPhone;

    // Success Messages
    case 'orderPlacedSuccessfully':
      return l10n.orderPlacedSuccessfully;
    case 'pleaseSelectAddress':
      return l10n.pleaseSelectAddress;
    case 'orderCreatedSuccessfully':
      return l10n.orderCreatedSuccessfully;
    case 'addressCreatedSuccessfully':
      return l10n.addressCreatedSuccessfully;
    case 'addressUpdatedSuccessfully':
      return l10n.addressUpdatedSuccessfully;
    case 'addressDeletedSuccessfully':
      return l10n.addressDeletedSuccessfully;
    case 'defaultAddressUpdated':
      return l10n.defaultAddressUpdated;

    // Greetings
    case 'goodMorning':
      return l10n.goodMorning;
    case 'goodAfternoon':
      return l10n.goodAfternoon;
    case 'goodEvening':
      return l10n.goodEvening;
    case 'hey':
      return l10n.hey;

    // Units & Status
    case 'min':
      return l10n.min;
    case 'free':
      return l10n.free;
    case 'closed':
      return l10n.closed;
    case 'open':
      return l10n.open;

    // Pricing
    case 'quantity':
      return l10n.quantity;
    case 'price':
      return l10n.price;
    case 'subtotal':
      return l10n.subtotal;
    case 'tax':
      return l10n.tax;
    case 'discount':
      return l10n.discount;

    // Network & Errors
    case 'noInternetConnection':
      return l10n.noInternetConnection;
    case 'serverError':
      return l10n.serverError;
    case 'somethingWentWrong':
      return l10n.somethingWentWrong;
    case 'pleaseTryAgain':
      return l10n.pleaseTryAgain;

    // Additional UI Strings
    case 'logOutConfirm':
      return l10n.logOutConfirm;
    case 'deleteAccount':
      return l10n.deleteAccount;
    case 'deleteAccountConfirm':
      return l10n.deleteAccountConfirm;
    case 'replaceCartItems':
      return l10n.replaceCartItems;
    case 'addNewItem':
      return l10n.addNewItem;
    case 'selectRating':
      return l10n.selectRating;
    case 'enterVerificationCodeFull':
      return l10n.enterVerificationCodeFull;
    case 'invalidCode':
      return l10n.invalidCode;
    case 'codeExpired':
      return l10n.codeExpired;
    case 'resendCodeSuccess':
      return l10n.resendCodeSuccess;
    case 'sort':
      return l10n.sort;
    case 'sortBy':
      return l10n.sortBy;
    case 'filterBy':
      return l10n.filterBy;
    case 'free_delivery':
      return l10n.free_delivery;
    case 'offers':
      return l10n.offers;
    case 'cuisines':
      return l10n.cuisines;
    case 'searchForStores':
      return l10n.searchForStores;
    case 'enterPromoCode':
      return l10n.enterPromoCode;
    case 'applyPromo':
      return l10n.applyPromo;
    case 'promoCode':
      return l10n.promoCode;
    case 'addItems':
      return l10n.addItems;
    case 'selectItems':
      return l10n.selectItems;
    case 'selectQuantity':
      return l10n.selectQuantity;
    case 'itemDetails':
      return l10n.itemDetails;
    case 'description':
      return l10n.description;
    case 'ingredients':
      return l10n.ingredients;
    case 'allergyInfo':
      return l10n.allergyInfo;
    case 'writeReview':
      return l10n.writeReview;
    case 'yourReview':
      return l10n.yourReview;
    case 'excellent':
      return l10n.excellent;
    case 'good':
      return l10n.good;
    case 'average':
      return l10n.average;
    case 'poor':
      return l10n.poor;
    case 'submitReview':
      return l10n.submitReview;
    case 'trackingOrder':
      return l10n.trackingOrder;
    case 'estimatedDelivery':
      return l10n.estimatedDelivery;
    case 'deliveryEstimate':
      return l10n.deliveryEstimate;
    case 'driverLocation':
      return l10n.driverLocation;
    case 'callDriver':
      return l10n.callDriver;
    case 'messageDriver':
      return l10n.messageDriver;
    case 'needHelp':
      return l10n.needHelp;
    case 'contactSupport':
      return l10n.contactSupport;
    case 'selectPaymentMethod':
      return l10n.selectPaymentMethod;
    case 'paymentMethod':
      return l10n.paymentMethod;
    case 'selectCard':
      return l10n.selectCard;
    case 'enterCardDetails':
      return l10n.enterCardDetails;
    case 'expiryDateFormat':
      return l10n.expiryDateFormat;
    case 'saveForFutureUse':
      return l10n.saveForFutureUse;
    case 'securePayment':
      return l10n.securePayment;
    case 'processPayment':
      return l10n.processPayment;
    case 'paymentFailed':
      return l10n.paymentFailed;
    case 'tryAgain':
      return l10n.tryAgain;
    case 'paymentSuccessful':
      return l10n.paymentSuccessful;
    case 'editProfile':
      return l10n.editProfile;
    case 'changePassword':
      return l10n.changePassword;
    case 'currentPassword':
      return l10n.currentPassword;
    case 'newPassword':
      return l10n.newPassword;
    case 'confirmNewPassword':
      return l10n.confirmNewPassword;
    case 'passwordChanged':
      return l10n.passwordChanged;
    case 'updateProfile':
      return l10n.updateProfile;
    case 'profileUpdated':
      return l10n.profileUpdated;
    case 'notificationSettings':
      return l10n.notificationSettings;
    case 'orderUpdates':
      return l10n.orderUpdates;
    case 'promotions':
      return l10n.promotions;
    case 'pushNotifications':
      return l10n.pushNotifications;
    case 'emailNotifications':
      return l10n.emailNotifications;
    case 'smsNotifications':
      return l10n.smsNotifications;
    case 'accountSettings':
      return l10n.accountSettings;
    case 'about':
      return l10n.about;
    case 'version':
      return l10n.version;
    case 'rateApp':
      return l10n.rateApp;
    case 'shareApp':
      return l10n.shareApp;
    case 'reportIssue':
      return l10n.reportIssue;
    case 'selectAllergy':
      return l10n.selectAllergy;
    case 'dietary':
      return l10n.dietary;
    case 'vegetarian':
      return l10n.vegetarian;
    case 'vegan':
      return l10n.vegan;
    case 'glutenFree':
      return l10n.glutenFree;
    case 'noNuts':
      return l10n.noNuts;
    case 'halal':
      return l10n.halal;
    case 'kosher':
      return l10n.kosher;
    case 'noSpicy':
      return l10n.noSpicy;
    case 'addSpecialRequest':
      return l10n.addSpecialRequest;
    case 'specialInstructions':
      return l10n.specialInstructions;
    case 'orderSummary':
      return l10n.orderSummary;
    case 'itemsCount':
      return l10n.itemsCount;
    case 'deliveryCharge':
      return l10n.deliveryCharge;
    case 'serviceFee':
      return l10n.serviceFee;
    case 'tipDriver':
      return l10n.tipDriver;
    case 'tipAmount':
      return l10n.tipAmount;
    case 'noCash':
      return l10n.noCash;
    case 'noChange':
      return l10n.noChange;
    case 'changeAmount':
      return l10n.changeAmount;
    case 'paymentConfirmation':
      return l10n.paymentConfirmation;
    case 'transactionId':
      return l10n.transactionId;
    case 'confirmOrder':
      return l10n.confirmOrder;
    case 'cancelOrder':
      return l10n.cancelOrder;
    case 'cancelOrderConfirm':
      return l10n.cancelOrderConfirm;
    case 'orderCancelled':
      return l10n.orderCancelled;
    case 'refundInitiated':
      return l10n.refundInitiated;
    case 'refundPending':
      return l10n.refundPending;
    case 'refundCompleted':
      return l10n.refundCompleted;
    case 'reportProblem':
      return l10n.reportProblem;
    case 'problemType':
      return l10n.problemType;
    case 'wrongItems':
      return l10n.wrongItems;
    case 'damageFood':
      return l10n.damageFood;
    case 'missingItems':
      return l10n.missingItems;
    case 'coldFood':
      return l10n.coldFood;
    case 'incompleteOrder':
      return l10n.incompleteOrder;
    case 'other':
      return l10n.other;
    case 'describeProblem':
      return l10n.describeProblem;
    case 'submitReport':
      return l10n.submitReport;
    case 'reportSubmitted':
      return l10n.reportSubmitted;
    case 'weWillAssist':
      return l10n.weWillAssist;
    case 'browseMenu':
      return l10n.browseMenu;
    case 'viewDetails':
      return l10n.viewDetails;
    case 'moreInfo':
      return l10n.moreInfo;
    case 'lessInfo':
      return l10n.lessInfo;
    case 'showMore':
      return l10n.showMore;
    case 'showLess':
      return l10n.showLess;
    case 'pleasePatienceLoading':
      return l10n.pleasePatienceLoading;
    case 'noData':
      return l10n.noData;
    case 'emptyList':
      return l10n.emptyList;
    case 'trySearching':
      return l10n.trySearching;
    case 'invalidInput':
      return l10n.invalidInput;
    case 'required':
      return l10n.required;
    case 'termsAccepted':
      return l10n.termsAccepted;
    case 'agreeToTerms':
      return l10n.agreeToTerms;
    case 'privacyAccepted':
      return l10n.privacyAccepted;
    case 'agreeToPrivacy':
      return l10n.agreeToPrivacy;
    case 'selectLanguage':
      return l10n.selectLanguage;
    case 'selectCurrency':
      return l10n.selectCurrency;
    case 'moreOptions':
      return l10n.moreOptions;
    case 'copyAddress':
      return l10n.copyAddress;
    case 'shareLocation':
      return l10n.shareLocation;
    case 'getDirections':
      return l10n.getDirections;
    case 'navigateTo':
      return l10n.navigateTo;
    case 'closeStore':
      return l10n.closeStore;
    case 'storeWillOpenAt':
      return l10n.storeWillOpenAt;
    case 'outOfStock':
      return l10n.outOfStock;
    case 'unavailable':
      return l10n.unavailable;
    case 'saleBadge':
      return l10n.saleBadge;
    case 'newBadge':
      return l10n.newBadge;
    case 'popularBadge':
      return l10n.popularBadge;
    case 'trendingBadge':
      return l10n.trendingBadge;
    case 'bestSellerBadge':
      return l10n.bestSellerBadge;
    case 'limitedTime':
      return l10n.limitedTime;
    case 'expiresIn':
      return l10n.expiresIn;
    case 'noStoresFound':
      return l10n.noStoresFound;
    case 'tryAnotherSearch':
      return l10n.tryAnotherSearch;
    case 'enterAtLeastCharacters':
      return l10n.enterAtLeastCharacters;

    // Wallet
    case 'wallet':
      return l10n.wallet;
    case 'yourWallet':
      return l10n.yourWallet;
    case 'availableBalance':
      return l10n.availableBalance;
    case 'topUp':
      return l10n.topUp;
    case 'topUpWallet':
      return l10n.topUpWallet;
    case 'topUpSuccessful':
      return l10n.topUpSuccessful;
    case 'send':
      return l10n.send;
    case 'comingSoon':
      return l10n.comingSoon;
    case 'recentTransactions':
      return l10n.recentTransactions;
    case 'noTransactions':
      return l10n.noTransactions;
    case 'totalEarned':
      return l10n.totalEarned;
    case 'totalSpent':
      return l10n.totalSpent;
    case 'balanceAfter':
      return l10n.balanceAfter;
    case 'enterAmount':
      return l10n.enterAmount;
    case 'quickSelect':
      return l10n.quickSelect;
    case 'enterValidAmount':
      return l10n.enterValidAmount;
    case 'proceedTopUp':
      return l10n.proceedTopUp;
    case 'errorLoadingWallet':
      return l10n.errorLoadingWallet;
    case 'inactive':
      return l10n.inactive;

    // Default - return the key if not found
    default:
      return key;
  }
}
